[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  CI = "true"

# Optional: redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


